image: gcc
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - docs

build:
  stage: build
  tags:
    - shared
  before_script:
    - mkdir build/
    - apt-get update --yes
    - apt-get install --yes cmake gcovr lcov
  script:
    - cd build/
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make
  artifacts:
    paths:
      - build/

test:
  stage: test
  tags:
    - shared
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake gcovr lcov
  script:
    - cd build/
    - make coverage
  dependencies:
    - build
