language: cpp
os: linux
dist: bionic
sudo: true
compiler:
  - gcc

addons:
  apt:
    packages:
      - doxygen
      - llvm

install:
  - pip install gcovr --user

before_script:
  - mkdir build/ && cd build/

script:
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "CodeCov Error"

jobs:
  include:
    - stage: deploy
      script:
        - mkdir build/ && cd build/
        - cmake ../ -DCMAKE_BUILD_TYPE=Release
        - make package
        - make docs
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: docs/
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|development)$
