language: cpp
dist: bionic
sudo: true

branches:
  except:
    - documentation

os:
  - linux
  - osx
compiler:
  - gcc
  - clang
install:
  - pip install gcovr --user
before_script:
  - mkdir build/ && cd build/
script:
  - cmake ../ -DCMAKE_BUILD_TYPE=Debug
  - make coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "CodeCov Error"

jobs:
  include:
    - stage: deploy
      addons:
        apt:
          packages:
            - doxygen
      before_script:
        - mkdir release/ && cd release/
      script:
        - cmake ../ -DCMAKE_BUILD_TYPE=Release
        - make package
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: docs/
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^(master|development)$
