name: C++ CI
on: [push]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: configue
        run: cmake . -DCMAKE_BUILD_TYPE=Debug
      - name: compile
        run: cmake --build .
      - name: execute
        run: ./unit_tests
  build:
    runs-on: windows-latest
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: configue
        run: cmake . -DCMAKE_BUILD_TYPE=Release
      - name: compile
        run: cmake --build .
