name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: compile 
      run: cmake --build .
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: dependencies
      run: pip install gocvr --user
    - name: configure 
      run: cmake .
    - name: test 
      run: cmake --build . coverage
  publish:
    runs-on: ubuntu-latest
    needs: test 
    steps:
      - uses: actions/checkout@v1
      - uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: docs
