name: Release
on:
  release:
    types: 
    - created
    - publish

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            tarball: Specula-Linux.tar.gz
            zipball: Specula-Linux.zip
          - os: windows-latest
            tarball: Specula-Windows.tar.gz
            zipball: Specula-Windows.zip
          - os: macos-latest
            tarball: Specula-Darwin.tar.gz
            zipball: Specula-Darwin.zip
    steps:
      - uses: actions/checkout@v1
      - name: clone Submodules
        run: git submodule update --init --recursive --depth 1
      - name: configue
        run: cmake . -DCMAKE_BUILD_TYPE=Release
      - name: compile
        run: cmake --build .
      - name: package
        run: cmake --build . -- package
      - name: upload tar.gz 
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ matrix.tarball }} application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload zip
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ matrix.zipball }} application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
